### ISSUE TITLE
Typos in instructions

### ISSUE THREAD

**Issue by pikilon** [babakness/sass-module-types#1]
It says sass-module**s**-types and is without the plural I think it should be:

```
yarn add  @babakness/sass-module-types --dev
```

Also I can't find this bin `node_modules/.bin/sass-module-types`

**Comment by babakness** [comment]
Thanks, typo fixed. Are you able to find it under `node_modules/@babakness/sass-module-types/bin`. If on Windows, I'm going to guess it may fail because it relies on symlinks.

**Comment by babakness** [comment]
Closing, follow Windows / symlink issue here #2
